name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: .   # Ensure this matches your React project folder

      - name: Build the project
        run: npm run build
        working-directory: .   # Same here

      - name: Deploy via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "🚀 Setting up SSH and creating remote directory..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no rishabhvyas@178.16.137.226 "mkdir -p /home/rishabhvyas/ict/build/"
          echo "🚀 Uploading build files to VPS..."
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" build/ rishabhvyas@178.16.137.226:/home/rishabhvyas/ict/build/
          echo "✅ Deployment completed!"